### GET /products
GET http://{{server}}:{{port}}/api/products

### GET /products?ative=true
GET http://{{server}}:{{port}}/api/products?active=false

### POST /products
POST http://{{server}}:{{port}}/api/products
Content-Type: application/json

{
"title":"kukumber",
"price":1.99,
"active":true
}

### PUT /products/{id}
PUT http://{{server}}:{{port}}/api/products/4
Content-Type: application/json

{
  "title":"kukumber 1 kg",
  "price":1.06,
  "active":false
}
